spring.application.name=school-management

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ================================
#  JWT CONFIGURATION
# ================================
# Secret key for signing tokens (make it long random)
jwt.secret=mySecretKeyThatIsVeryLongAndSecureForJWTSigning2024SchoolApp

#Token expiration: 24 hours in milliseconds
# 86400000 = 24 * 60 * 60 * 1000
jwt.expiration = 86400000
